# Generated by Django 3.2.7 on 2021-09-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_upvote_post_up_votes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="link",
            field=models.URLField(max_length=256, unique=True, verbose_name="Link"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=256, unique=True, verbose_name="Title"),
        ),
    ]
