# Generated by Django 3.2.7 on 2021-09-16 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20210915_1816"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="comment",
            table="api_comment",
        ),
        migrations.AlterModelTable(
            name="post",
            table="api_post",
        ),
    ]
